name: flutter_fortune_wheel_example
version: 1.0.0

publish_to: "none"

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  flutter_hooks: ^0.20.5
  flutter_fortune_wheel:
    path: ../
  go_router: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.0
  effective_dart: ^1.3.2

flutter:
  uses-material-design: true
